name: D:\ML_projects\heart-disease-project\env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.10.0=py313haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py313h02ab6af_0
  - asttokens=3.0.0=py313haa95532_0
  - async-lru=2.0.5=py313haa95532_0
  - attrs=25.4.0=py313haa95532_0
  - babel=2.16.0=py313haa95532_0
  - beautifulsoup4=4.13.5=py313haa95532_0
  - bleach=6.2.0=py313haa95532_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.1=py313haa95532_0
  - contourpy=1.3.3=py313hf069bd2_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py313h885b0b7_0
  - decorator=5.2.1=py313haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - double-conversion=3.3.1=he0c23c2_0
  - executing=2.2.1=py313haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py313hd650c13_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=py313haa95532_0
  - harfbuzz=12.1.0=h5f2951f_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - icu=75.1=he0c23c2_0
  - idna=3.7=py313haa95532_0
  - ipykernel=6.30.1=py313haa95532_0
  - ipython=9.5.0=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - ipywidgets=8.1.5=py313haa95532_0
  - jedi=0.19.2=py313haa95532_0
  - jinja2=3.1.6=py313haa95532_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.9.25=py313haa95532_0
  - jsonschema=4.25.0=py313haa95532_0
  - jsonschema-specifications=2023.7.1=py313haa95532_0
  - jupyter=1.1.1=py313haa95532_0
  - jupyter-lsp=2.2.5=py313haa95532_0
  - jupyter_client=8.6.3=py313haa95532_0
  - jupyter_console=6.6.3=py313haa95532_1
  - jupyter_core=5.8.1=py313haa95532_0
  - jupyter_events=0.12.0=py313haa95532_0
  - jupyter_server=2.16.0=py313haa95532_0
  - jupyter_server_terminals=0.5.3=py313haa95532_0
  - jupyterlab=4.4.7=py313haa95532_0
  - jupyterlab_pygments=0.3.0=py313haa95532_0
  - jupyterlab_server=2.27.3=py313haa95532_0
  - jupyterlab_widgets=3.0.15=py313haa95532_0
  - kiwisolver=1.4.9=py313h1a38498_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.4=default_ha2db4b5_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.0=hd9c3897_1
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libsodium=1.0.20=h83e8143_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.1=h550210a_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib=3.10.7=py313hfa70ccb_0
  - matplotlib-base=3.10.7=py313he1ded55_0
  - matplotlib-inline=0.1.7=py313haa95532_0
  - mistune=3.1.2=py313haa95532_0
  - mkl=2024.2.2=h57928b3_16
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=py313haa95532_0
  - nbconvert=7.16.6=py313haa95532_0
  - nbconvert-core=7.16.6=py313haa95532_0
  - nbconvert-pandoc=7.16.6=py313haa95532_0
  - nbformat=5.10.4=py313haa95532_0
  - nest-asyncio=1.6.0=py313haa95532_0
  - notebook=7.4.5=py313haa95532_0
  - notebook-shim=0.2.4=py313haa95532_0
  - numpy=2.3.4=py313hce7ae62_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - overrides=7.4.0=py313haa95532_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py313haa95532_0
  - parso=0.8.4=py313haa95532_0
  - pcre2=10.46=h3402e2f_0
  - pillow=11.3.0=py313hf455b62_3
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.3.7=py313haa95532_0
  - prometheus_client=0.21.1=py313haa95532_0
  - prompt-toolkit=3.0.52=py313haa95532_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - psutil=7.0.0=py313h02ab6af_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=py313haa95532_0
  - pycparser=2.23=py313haa95532_0
  - pygments=2.19.1=py313haa95532_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py313h475ba69_1
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.9=h09917c8_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.20.0=py313haa95532_0
  - python-json-logger=3.2.1=py313haa95532_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py313h885b0b7_0
  - pywinpty=2.0.15=py313h72d21ff_0
  - pyyaml=6.0.2=py313h827c3e9_0
  - pyzmq=27.1.0=py313h7149c55_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_0
  - qtconsole=5.7.0=py313haa95532_0
  - qtpy=2.4.3=py313haa95532_0
  - referencing=0.30.2=py313haa95532_0
  - requests=2.32.5=py313haa95532_0
  - rfc3339-validator=0.1.4=py313haa95532_0
  - rfc3986-validator=0.1.1=py313haa95532_0
  - rpds-py=0.22.3=py313h636fa0f_0
  - scikit-learn=1.7.2=py313he28f1d7_0
  - scipy=1.16.2=py313h62a08ca_0
  - seaborn=0.13.2=py313haa95532_3
  - send2trash=1.8.2=py313haa95532_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.0=py313haa95532_0
  - soupsieve=2.5=py313haa95532_0
  - stack_data=0.6.3=py313haa95532_0
  - tbb=2021.13.0=h18a62a1_3
  - terminado=0.18.1=py313haa95532_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py313haa95532_0
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py313h5ea7bf4_1
  - traitlets=5.14.3=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py313haa95532_0
  - webencodings=0.5.1=py313haa95532_2
  - websocket-client=1.8.0=py313haa95532_0
  - widgetsnbextension=4.0.13=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - winpty=0.4.3=4
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - catboost==1.2.8
      - graphviz==0.21
      - narwhals==2.13.0
      - plotly==6.5.0
      - xgboost==3.1.2
prefix: D:\ML_projects\heart-disease-project\env
